# Fibonacci number is a sequence of numbers that is generated by the sum of the last two numbers of the sequence. 
# Starting with two initial numbers 0 and 1, the next number in sequence is 1 (0 + 1), 
# followed by 2 (1 + 1), followed by 3 (1 + 2), and so on. Therefore, the sequence would look as follows: 

# 0, 1, 1, 2, 3, 5, 8, 13, … 

# Let F(n) be the nth number in Fibonacci sequence. 
# Then, F(1) = 0, F(2) = 1, …, F(8) = 13, ... (or F(1) = 0, F(2) = 1, and F(k) = F(k-1) + F(k-2) for k > 1). 

# To make it less trivial, we introduce a modified Fibonacci sequence where MF(1) = 0, MF(2) = 1, 
# and MF(k) = MF(k-1)1/2 + MF(k-2)1.1 for k>1. 

# Your task for module 1 is to write a code that prints the modified Fibonacci sequence 
# of one hundred numbers using Python. 


#function to generate modified Fibonacci
def modifiedFibo(num):
    first = 0   
    second = 1  
    if num == 0: #if number k is 0, then return 0 as the result
        return first
    elif num == 1: #if number k is 1, then return 1 as the result
        return second
    else: #otherwise, if number k is 2 or above, then:
        for i in range (2, num+1):
            third = first**1.1 + second**0.5 #the result is k(2-1)**1.1 + k(k-1)**0.5
            first = second #variable "first" now has the value of variable "second"
            second = third #variable "second" now has the value of most recent k, which is "third"
        return third


index = 0
num = 0
while index <= 100: #print 100 modified Fibonacci numbers on the terminal
    print("index", index, "value", modifiedFibo(num))
    index += 1
    num += 1
